### PR TITLE
Edit navigation format

### PR DESCRIPTION
**Pull request by tatarianBarbarian**
This one changes navigation format to new one that described in https://github.com/evilmartians/astro-typedoc/issues/25#issuecomment-1713743440

Added new test environment -- project with multiple entry points.

Also changed templates. 
Now navigation looks the same as before for single entry point, but for multiple entries it looks like this:

image

### CODE REVIEW

**Comment by tatarianBarbarian** [comment]
To make it a bit more clear: Nanostores has one entry point which accumulates other `index.d.ts` from file like `map`, `atom`, etc. 

I set up new environment by picking some of them from these folders, not from the root `index.d.ts`.

**Comment by tatarianBarbarian** [comment]
There is also new problem related to Astro and TypeDoc -- if project for documentation is on upper level, then TypeDoc generates it's name with `_` symbol. So we getting following structure:

image

Which is not working for Astro. It works only with folders without any underscores for pages. 
Will fix it with another PR.

**Comment by ai** [comment]
> To make it a bit more clear: Nanostores has one entry point which accumulates other index.d.ts from file like map, atom, etc.

For Nano Stores we will need to use `index.d.ts` from `nanostores`, `@nanostores/router`, etc. Can we add it to the test (to be sure that `atom` from `nanostores` and `atom` from `@nanostores/router` will be the same?

**Comment by tatarianBarbarian** [comment]
Sure, I'll add it then.

**Review by ai — APPROVED** [review]

**Pull request merged**
