### PR TITLE
Add markdown content

### PR DESCRIPTION
**Pull request by tatarianBarbarian**
From this point pages that are generated by utility have relevant content: description, type definition, etc.

Each entity has its own page.

### CODE REVIEW

**Comment by tatarianBarbarian** [comment]
Now code can generate contentful markdown pages.
image

The next step is to make it generate separate page for each entity, because now they are in one big README file, and a few interfaces have their own folder.

**Comment by ai** [comment]
Nice, exatcly what we planned for Friday. I will check it later today.

**Comment by tatarianBarbarian** [comment]
@ai
I've enhanced the way pages are generated -- installed newer version of `typedoc-plugin-markdown`.
Now, each entity lives in its own file. 
The structure is following:

```
.
└── output-folder/
    ├── functions/
    │   ├── function.action.md
    │   └── function.atom.md
    ├── type-aliases/
    │   ├── type-alias.AllPaths.md
    │   └── type-alias.Atom.md
    ├── interfaces/
    │   └── ...
    └── variables/
        └── ...
```

It follows to the typedoc groups of reflections structure.

**Comment by ai** [comment]
And was the structure before?

**Review by ai — APPROVED** [review]

**Pull request merged**
